//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Course_Registration
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Students.
    /// </summary>
    // *** Start programmer edit section *** (Students CustomAttributes)

    // *** End programmer edit section *** (Students CustomAttributes)
    [AutoAltered()]
    [Caption("Student Registration")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("StudentsE", new string[] {
            "Name as \'Name\'",
            "Surname as \'Surname\'",
            "DateOfBirth as \'Date of birth\'",
            "Age as \'Age\'",
            "Gener as \'Gener\'",
            "Course as \'Course\'",
            "Course.CourseType as \'Course type\'"}, Hidden=new string[] {
            "Course.CourseType"})]
    [MasterViewDefineAttribute("StudentsE", "Course", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "CourseType")]
    [View("StudentsL", new string[] {
            "Name as \'Name\'",
            "Surname as \'Surname\'",
            "DateOfBirth as \'Date of birth\'",
            "Age as \'Age\'",
            "Gener as \'Gener\'",
            "Course.CourseType as \'Course type\'"})]
    public class Students : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private System.DateTime fDateOfBirth;
        
        private IIS.Course_Registration.tGenderType fGener;
        
        private string fSurname;
        
        private int fAge;
        
        private IIS.Course_Registration.Course fCourse;
        
        // *** Start programmer edit section *** (Students CustomMembers)

        // *** End programmer edit section *** (Students CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Students.Name CustomAttributes)

        // *** End programmer edit section *** (Students.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Students.Name Get start)

                // *** End programmer edit section *** (Students.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Students.Name Get end)

                // *** End programmer edit section *** (Students.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Students.Name Set start)

                // *** End programmer edit section *** (Students.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Students.Name Set end)

                // *** End programmer edit section *** (Students.Name Set end)
            }
        }
        
        /// <summary>
        /// DateOfBirth.
        /// </summary>
        // *** Start programmer edit section *** (Students.DateOfBirth CustomAttributes)

        // *** End programmer edit section *** (Students.DateOfBirth CustomAttributes)
        public virtual System.DateTime DateOfBirth
        {
            get
            {
                // *** Start programmer edit section *** (Students.DateOfBirth Get start)

                // *** End programmer edit section *** (Students.DateOfBirth Get start)
                System.DateTime result = this.fDateOfBirth;
                // *** Start programmer edit section *** (Students.DateOfBirth Get end)

                // *** End programmer edit section *** (Students.DateOfBirth Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Students.DateOfBirth Set start)

                // *** End programmer edit section *** (Students.DateOfBirth Set start)
                this.fDateOfBirth = value;
                // *** Start programmer edit section *** (Students.DateOfBirth Set end)

                // *** End programmer edit section *** (Students.DateOfBirth Set end)
            }
        }
        
        /// <summary>
        /// Gener.
        /// </summary>
        // *** Start programmer edit section *** (Students.Gener CustomAttributes)

        // *** End programmer edit section *** (Students.Gener CustomAttributes)
        public virtual IIS.Course_Registration.tGenderType Gener
        {
            get
            {
                // *** Start programmer edit section *** (Students.Gener Get start)

                // *** End programmer edit section *** (Students.Gener Get start)
                IIS.Course_Registration.tGenderType result = this.fGener;
                // *** Start programmer edit section *** (Students.Gener Get end)

                // *** End programmer edit section *** (Students.Gener Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Students.Gener Set start)

                // *** End programmer edit section *** (Students.Gener Set start)
                this.fGener = value;
                // *** Start programmer edit section *** (Students.Gener Set end)

                // *** End programmer edit section *** (Students.Gener Set end)
            }
        }
        
        /// <summary>
        /// Surname.
        /// </summary>
        // *** Start programmer edit section *** (Students.Surname CustomAttributes)

        // *** End programmer edit section *** (Students.Surname CustomAttributes)
        [StrLen(255)]
        public virtual string Surname
        {
            get
            {
                // *** Start programmer edit section *** (Students.Surname Get start)

                // *** End programmer edit section *** (Students.Surname Get start)
                string result = this.fSurname;
                // *** Start programmer edit section *** (Students.Surname Get end)

                // *** End programmer edit section *** (Students.Surname Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Students.Surname Set start)

                // *** End programmer edit section *** (Students.Surname Set start)
                this.fSurname = value;
                // *** Start programmer edit section *** (Students.Surname Set end)

                // *** End programmer edit section *** (Students.Surname Set end)
            }
        }
        
        /// <summary>
        /// Age.
        /// </summary>
        // *** Start programmer edit section *** (Students.Age CustomAttributes)

        // *** End programmer edit section *** (Students.Age CustomAttributes)
        public virtual int Age
        {
            get
            {
                // *** Start programmer edit section *** (Students.Age Get start)

                // *** End programmer edit section *** (Students.Age Get start)
                int result = this.fAge;
                // *** Start programmer edit section *** (Students.Age Get end)

                // *** End programmer edit section *** (Students.Age Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Students.Age Set start)

                // *** End programmer edit section *** (Students.Age Set start)
                this.fAge = value;
                // *** Start programmer edit section *** (Students.Age Set end)

                // *** End programmer edit section *** (Students.Age Set end)
            }
        }
        
        /// <summary>
        /// Students.
        /// </summary>
        // *** Start programmer edit section *** (Students.Course CustomAttributes)

        // *** End programmer edit section *** (Students.Course CustomAttributes)
        [NotNull()]
        public virtual IIS.Course_Registration.Course Course
        {
            get
            {
                // *** Start programmer edit section *** (Students.Course Get start)

                // *** End programmer edit section *** (Students.Course Get start)
                IIS.Course_Registration.Course result = this.fCourse;
                // *** Start programmer edit section *** (Students.Course Get end)

                // *** End programmer edit section *** (Students.Course Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Students.Course Set start)

                // *** End programmer edit section *** (Students.Course Set start)
                this.fCourse = value;
                // *** Start programmer edit section *** (Students.Course Set end)

                // *** End programmer edit section *** (Students.Course Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "StudentsE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View StudentsE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("StudentsE", typeof(IIS.Course_Registration.Students));
                }
            }
            
            /// <summary>
            /// "StudentsL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View StudentsL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("StudentsL", typeof(IIS.Course_Registration.Students));
                }
            }
        }
    }
}
