//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Course_Registration
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Choosing courses.
    /// </summary>
    // *** Start programmer edit section *** (tCourseType CustomAttributes)

    // *** End programmer edit section *** (tCourseType CustomAttributes)
    public enum tCourseType
    {
        
        // *** Start programmer edit section *** (tCourseType.Financial CustomAttributes)

        // *** End programmer edit section *** (tCourseType.Financial CustomAttributes)
        [Caption("Finance and credit")]
        Financial,
        
        // *** Start programmer edit section *** (tCourseType.Mathematics CustomAttributes)

        // *** End programmer edit section *** (tCourseType.Mathematics CustomAttributes)
        [Caption("Elective Mathematics")]
        Mathematics,
        
        // *** Start programmer edit section *** (tCourseType.Information CustomAttributes)

        // *** End programmer edit section *** (tCourseType.Information CustomAttributes)
        [Caption("Business Analytics")]
        Information,
        
        // *** Start programmer edit section *** (tCourseType.Buisness CustomAttributes)

        // *** End programmer edit section *** (tCourseType.Buisness CustomAttributes)
        [Caption("Management Studies")]
        Buisness,
        
        // *** Start programmer edit section *** (tCourseType.Theology CustomAttributes)

        // *** End programmer edit section *** (tCourseType.Theology CustomAttributes)
        [Caption("Theology")]
        Theology,
        
        // *** Start programmer edit section *** (tCourseType.Philosophy CustomAttributes)

        // *** End programmer edit section *** (tCourseType.Philosophy CustomAttributes)
        [Caption("Philosophy Studies")]
        Philosophy,
        
        // *** Start programmer edit section *** (tCourseType.Web CustomAttributes)

        // *** End programmer edit section *** (tCourseType.Web CustomAttributes)
        [Caption("Web Development")]
        Web,
        
        // *** Start programmer edit section *** (tCourseType.Law CustomAttributes)

        // *** End programmer edit section *** (tCourseType.Law CustomAttributes)
        [Caption("Law")]
        Law,
    }
}
