//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Course_Registration
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Gender Type option.
    /// </summary>
    // *** Start programmer edit section *** (tGenderType CustomAttributes)

    // *** End programmer edit section *** (tGenderType CustomAttributes)
    public enum tGenderType
    {
        
        // *** Start programmer edit section *** (tGenderType.Male CustomAttributes)

        // *** End programmer edit section *** (tGenderType.Male CustomAttributes)
        [Caption("Male")]
        Male,
        
        // *** Start programmer edit section *** (tGenderType.Female CustomAttributes)

        // *** End programmer edit section *** (tGenderType.Female CustomAttributes)
        [Caption("Female")]
        Female,
    }
}
